# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noplay/code/gns3/gns3-gui/gns3/modules/iou/ui/iou_device_wizard.ui'
#
# Created: Wed Apr 15 18:14:52 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_IOUDeviceWizard(object):

    def setupUi(self, IOUDeviceWizard):
        IOUDeviceWizard.setObjectName(_fromUtf8("IOUDeviceWizard"))
        IOUDeviceWizard.resize(585, 423)
        IOUDeviceWizard.setModal(True)
        self.uiServerWizardPage = QtGui.QWizardPage()
        self.uiServerWizardPage.setObjectName(_fromUtf8("uiServerWizardPage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.uiServerWizardPage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiServerTypeGroupBox = QtGui.QGroupBox(self.uiServerWizardPage)
        self.uiServerTypeGroupBox.setObjectName(_fromUtf8("uiServerTypeGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.uiServerTypeGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiRemoteRadioButton = QtGui.QRadioButton(self.uiServerTypeGroupBox)
        self.uiRemoteRadioButton.setChecked(True)
        self.uiRemoteRadioButton.setObjectName(_fromUtf8("uiRemoteRadioButton"))
        self.horizontalLayout.addWidget(self.uiRemoteRadioButton)
        self.uiCloudRadioButton = QtGui.QRadioButton(self.uiServerTypeGroupBox)
        self.uiCloudRadioButton.setObjectName(_fromUtf8("uiCloudRadioButton"))
        self.horizontalLayout.addWidget(self.uiCloudRadioButton)
        self.uiLocalRadioButton = QtGui.QRadioButton(self.uiServerTypeGroupBox)
        self.uiLocalRadioButton.setObjectName(_fromUtf8("uiLocalRadioButton"))
        self.horizontalLayout.addWidget(self.uiLocalRadioButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.uiServerTypeGroupBox, 0, 0, 1, 1)
        self.uiRemoteServersGroupBox = QtGui.QGroupBox(self.uiServerWizardPage)
        self.uiRemoteServersGroupBox.setObjectName(_fromUtf8("uiRemoteServersGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.uiRemoteServersGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.uiLoadBalanceCheckBox = QtGui.QCheckBox(self.uiRemoteServersGroupBox)
        self.uiLoadBalanceCheckBox.setChecked(True)
        self.uiLoadBalanceCheckBox.setObjectName(_fromUtf8("uiLoadBalanceCheckBox"))
        self.gridLayout_7.addWidget(self.uiLoadBalanceCheckBox, 0, 0, 1, 2)
        self.uiRemoteServersLabel = QtGui.QLabel(self.uiRemoteServersGroupBox)
        self.uiRemoteServersLabel.setObjectName(_fromUtf8("uiRemoteServersLabel"))
        self.gridLayout_7.addWidget(self.uiRemoteServersLabel, 1, 0, 1, 1)
        self.uiRemoteServersComboBox = QtGui.QComboBox(self.uiRemoteServersGroupBox)
        self.uiRemoteServersComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiRemoteServersComboBox.sizePolicy().hasHeightForWidth())
        self.uiRemoteServersComboBox.setSizePolicy(sizePolicy)
        self.uiRemoteServersComboBox.setObjectName(_fromUtf8("uiRemoteServersComboBox"))
        self.gridLayout_7.addWidget(self.uiRemoteServersComboBox, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.uiRemoteServersGroupBox, 1, 0, 1, 1)
        IOUDeviceWizard.addPage(self.uiServerWizardPage)
        self.uiNameImageWizardPage = QtGui.QWizardPage()
        self.uiNameImageWizardPage.setObjectName(_fromUtf8("uiNameImageWizardPage"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiNameImageWizardPage)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.uiNameLabel = QtGui.QLabel(self.uiNameImageWizardPage)
        self.uiNameLabel.setObjectName(_fromUtf8("uiNameLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.uiNameLabel)
        self.uiNameLineEdit = QtGui.QLineEdit(self.uiNameImageWizardPage)
        self.uiNameLineEdit.setObjectName(_fromUtf8("uiNameLineEdit"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.uiNameLineEdit)
        self.verticalLayout_2.addLayout(self.formLayout_7)
        self.groupBox = QtGui.QGroupBox(self.uiNameImageWizardPage)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiExistingImageRadioButton = QtGui.QRadioButton(self.groupBox)
        self.uiExistingImageRadioButton.setChecked(True)
        self.uiExistingImageRadioButton.setObjectName(_fromUtf8("uiExistingImageRadioButton"))
        self.horizontalLayout_2.addWidget(self.uiExistingImageRadioButton)
        self.uiNewImageRadioButton = QtGui.QRadioButton(self.groupBox)
        self.uiNewImageRadioButton.setChecked(False)
        self.uiNewImageRadioButton.setObjectName(_fromUtf8("uiNewImageRadioButton"))
        self.horizontalLayout_2.addWidget(self.uiNewImageRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.uiTypeLabel = QtGui.QLabel(self.groupBox)
        self.uiTypeLabel.setObjectName(_fromUtf8("uiTypeLabel"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.uiTypeLabel)
        self.uiTypeComboBox = QtGui.QComboBox(self.groupBox)
        self.uiTypeComboBox.setObjectName(_fromUtf8("uiTypeComboBox"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.uiTypeComboBox)
        self.uiIOUImageLabel = QtGui.QLabel(self.groupBox)
        self.uiIOUImageLabel.setObjectName(_fromUtf8("uiIOUImageLabel"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.uiIOUImageLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uiIOUImageListComboBox = QtGui.QComboBox(self.groupBox)
        self.uiIOUImageListComboBox.setObjectName(_fromUtf8("uiIOUImageListComboBox"))
        self.horizontalLayout_5.addWidget(self.uiIOUImageListComboBox)
        self.uiIOUImageLineEdit = QtGui.QLineEdit(self.groupBox)
        self.uiIOUImageLineEdit.setObjectName(_fromUtf8("uiIOUImageLineEdit"))
        self.horizontalLayout_5.addWidget(self.uiIOUImageLineEdit)
        self.uiIOUImageToolButton = QtGui.QToolButton(self.groupBox)
        self.uiIOUImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiIOUImageToolButton.setObjectName(_fromUtf8("uiIOUImageToolButton"))
        self.horizontalLayout_5.addWidget(self.uiIOUImageToolButton)
        self.formLayout_8.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.formLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox)
        IOUDeviceWizard.addPage(self.uiNameImageWizardPage)

        self.retranslateUi(IOUDeviceWizard)
        QtCore.QMetaObject.connectSlotsByName(IOUDeviceWizard)

    def retranslateUi(self, IOUDeviceWizard):
        IOUDeviceWizard.setWindowTitle(_translate("IOUDeviceWizard", "New IOU device template", None))
        self.uiServerWizardPage.setTitle(_translate("IOUDeviceWizard", "Server", None))
        self.uiServerWizardPage.setSubTitle(_translate("IOUDeviceWizard", "Please choose a server type to run your new IOU device.", None))
        self.uiServerTypeGroupBox.setTitle(_translate("IOUDeviceWizard", "Server type", None))
        self.uiRemoteRadioButton.setText(_translate("IOUDeviceWizard", "Remote", None))
        self.uiCloudRadioButton.setText(_translate("IOUDeviceWizard", "Cloud", None))
        self.uiLocalRadioButton.setText(_translate("IOUDeviceWizard", "Local", None))
        self.uiRemoteServersGroupBox.setTitle(_translate("IOUDeviceWizard", "Remote servers", None))
        self.uiLoadBalanceCheckBox.setText(_translate("IOUDeviceWizard", "Load balance across all available remote servers", None))
        self.uiRemoteServersLabel.setText(_translate("IOUDeviceWizard", "Run on server:", None))
        self.uiNameImageWizardPage.setTitle(_translate("IOUDeviceWizard", "Name and image", None))
        self.uiNameImageWizardPage.setSubTitle(_translate("IOUDeviceWizard", "Please choose a descriptive name for the new IOU device and add an IOU image.", None))
        self.uiNameLabel.setText(_translate("IOUDeviceWizard", "Name:", None))
        self.groupBox.setTitle(_translate("IOUDeviceWizard", "Image", None))
        self.uiExistingImageRadioButton.setText(_translate("IOUDeviceWizard", "Existing image", None))
        self.uiNewImageRadioButton.setText(_translate("IOUDeviceWizard", "New Image", None))
        self.uiTypeLabel.setText(_translate("IOUDeviceWizard", "Type:", None))
        self.uiIOUImageLabel.setText(_translate("IOUDeviceWizard", "IOU image:", None))
        self.uiIOUImageToolButton.setText(_translate("IOUDeviceWizard", "&Browse...", None))
